### ISSUE TITLE
zlibjs version 0.1.7 is too big

### ISSUE THREAD

**Issue by qlqllu** [calvinmetcalf/jszip#2]
The version 2.1.1 depends on the zlibjs's 0.1.7, but this zlibjs version's size is too big, it's about 35M.
I tried the latest version of zlibjs -- v0.2.0, the size is about 7M.

So, please change the dependency if it works.

Thanks!

**Comment by calvinmetcalf** [comment]
updates are being done at [Stuk/jszip](https://github.com/Stuk/jszip) and if you got it from npm that's where you got it from.

**Comment by billxinli** [comment]
Any updates on this? Pulled down the latest shpjs and jszip is taking up 68M.

**Comment by calvinmetcalf** [comment]
@billxinli you are in the wrong repo see [Stuk/jszip](https://github.com/Stuk/jszip)

**Comment by billxinli** [comment]
@calvinmetcalf Yes, I realized that, I should have been more clear. I meant to say, https://github.com/calvinmetcalf/shapefile-js/blob/gh-pages/package.json#L41 is using this repo, and this repo is causing shapefile-js to be bloated.

**Comment by calvinmetcalf** [comment]
ah makes more sense
